version: 2
linters:
  enable:
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  enable-only-fast-linters: false

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m
  tests: true