run:
  go: "1.22"
  allow-parallel-runners: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unparam
    - unused
    - gci
    - gofmt
    - gofumpt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  
  gocyclo:
    min-complexity: 30
  
  govet:
    enable-all: true
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  staticcheck:
    checks: ["all"]
  
  unparam:
    check-exported: false
  
  gci:
    sections:
      - standard
      - default
      - prefix(lazygotest)
    custom-order: true
  
  gofmt:
    simplify: true
  
  gofumpt:
    module-path: lazygotest
    extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
    - path: internal/app/app.go
      linters:
        - gocyclo
      text: "cyclomatic complexity"
  exclude-use-default: false